### ISSUE TITLE
Authorized but missing read permission

### ISSUE THREAD

**Issue by jtzl** [opscode/chef#2536]
Greetings, I have just started with Chef 12 and followed the posted installation docs, creating my user and then associating this user with my organization.  However, when I `knife user list`, I get an error saying:
```
ERROR:  You authenticated successfully to https://x.x.x.x:443 as xxxxxxxx but you are not authorized for this action
Response:  missing read permission
```
On the server side, I see 403 forbidden, but so far as I can tell my user is associated properly with the organization...  Though, to that end, how do I list an organization's groups and identify which users are admins for the org?

**Comment by chr4** [comment]
Thanks @MasayaAoyama. This solved it for me. This desperately needs to be in the docs! There's not a single reference in neither https://docs.chef.io/server/install_server.html nor https://docs.chef.io/server/ covering workstation/knife configuration.

**Comment by jtzl** [comment]
I re-downloaded chef-server (via yum), and it appeared to be a patched file (chef-server-core-12.0.1-1.x86_64.rpm).  I did not re-experience the issue afterward.

**Comment by profversaggi** [comment]
Great work previous posters!

I followed your suggestions and ended up simply editing the knife.rb file and making the following small change:

In the knife.rb file, the URL has to include after the 443 a "/organizations/YOUR_ORG_NAME" (my case vis).

That worked.....see below.

SOLUTION:

log_level                :info
log_location             STDOUT
node_name                'versaggi'
client_key               '/home/versaggi/chef-repo/.chef/versaggi.pem'
validation_client_name   'vis-validator'
validation_key           '/home/versaggi/chef-repro/.chef/vis-validator.pem'
chef_server_url          'https://chef-server:443/organizations/vis'
syntax_check_cache_path  '/home/versaggi/chef-repo/.chef/syntax_check_cache'
cookbook_path [ '/home/versaggi/chef-repo/cookbooks' ]

**Comment by jamescott** [comment]
warning added to step #5:

http://docs.chef.io/upgrade_server.html#from-chef-server-osc

Thank you @irolller for alerting me. Wish I had seen this a bit sooner.

**Comment by juetten** [comment]
The extension of the URL with <server>/organizations/<my-org> saved me today =)

**Comment by vcpsong** [comment]
青山　様へ
貴重なご指導いただき大変助かりました。
今後ともよろしくお願いいたします。
宋
