### ISSUE TITLE
Installing Chef Analytics

### ISSUE THREAD

**Issue by oliver-whiteman** [opscode/chef#2579]
Not sure where to post this tbh so please let me know

Having issues with Chef Analytics install and getting a 404 error after I think everything is done. Cant see much relevance in logs so no idea where to go from here!

**Comment by danielsdeleo** [comment]
You can file tickets for general Chef Server issues here: https://github.com/opscode/chef-server/issues

Please include whatever information you can, including the exact command or action that resulted in the error and the output. For Chef Server, there's usually good info to be found via `chef-server-ctl tail`
