### ISSUE TITLE
UID already exists when setting the UID option for user on Mac OS

### ISSUE THREAD

**Issue by koldrid** [opscode/chef#2667]
We are working on managing our local Mac OS clients with Chef like all of our other servers. If we do not use the option "uid" everything proceeds as it should. As soon as we define the UID option we are told that UID is already in use. We have verified that is not the case before the chef run. However after the chef run the UID is updated in DSCL like we would want it to be.

================================================================================
Error executing action `create` on resource 'user[test]'
===============================================================================
    Chef::Exceptions::RequestedUIDUnavailable
    -----------------------------------------
    uid 510 is already in use

    Resource Declaration:
    ---------------------
           # In /tmp/kitchen/cache/cookbooks/local-users/recipes/default.rb

            64:   user("test") do
            65:     password "BLAH BLAH BLAH"
            66:     salt "BLAH BLAH BLAH"
            67:     iterations 25000
            68:     shell "/bin/bash"
            69:     uid 510
            70:     gid 601
            71:     home "/Users/test"
            72:     supports  :manage_home => true
            73:   end
            74:

    Compiled Resource:
    ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/local-users/recipes/default.rb:64:in `block in from_file'

           user("test") do
             action :create
             supports {:manage_home=>true}
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             username "test"
             uid 510
             gid 601
             home "/Users/test"
             shell "/bin/bash"
             password "BLAH BLAH BLAH"
             iterations 25000
             salt "BLAH BLAH BLAH"
             declared_type :user
             cookbook_name "local-users"
             recipe_name "default"
           end

       [2014-12-16T14:00:07-08:00] INFO: Running queued delayed notifications before re-raising exception

Running handlers:
       [2014-12-16T14:00:07-08:00] ERROR: Running exception handlers
       Running handlers complete

       [2014-12-16T14:00:07-08:00] ERROR: Exception handlers complete
       [2014-12-16T14:00:07-08:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
Chef Client failed. 1 resources updated in 5.877127 seconds
       [2014-12-16T14:00:07-08:00] ERROR: user[test] (local-users::default line 64) had an error: Chef::Exceptions::RequestedUIDUnavailable: uid 510 is already in use
       [2014-12-16T14:00:08-08:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

**Comment by jaymzh** [comment]
Holiday got in the way - if Pat gets to it today/tomorrow great, if not I'll send one.
