### ISSUE TITLE
Supermarket And Other Needed Certs Should Ship with Chef/ChefDK

### ISSUE THREAD

**Issue by sean-horn** [opscode/chef#2672]
As a customer, I don't want my workstation system to fail the first time I try to use the Chef client to download a cookbook or something from Supermarket.

If the certs are already in place, things will just work.

**Comment by danielsdeleo** [comment]
Without more detail, I'm gonna have to assume this is just a separate occurrence of the CA cert bundles bug where the curl project dropped the root certificate used by Amazon. To my knowledge, that was fixed for both ChefDK and Chef. If you have a repro on a current release, please provide debug logs and the like and we'll have a look.
