### ISSUE TITLE
macports provider has incorrect filters

### ISSUE THREAD

**Issue by jaymzh** [opscode/chef#2691]
macports currently provides `macports_package` to `os => 'mac_os_x'` but that's not an OS, it should be darwin.

**Comment by tyler-ball** [comment]
Yeah, I saw this same issue with homebrew - I just added both to the list of OSes (`os => ['mac_os_x', 'darwin']`).  I'm not sure if something changed with Ohai or in the latest version of OSX.

**Comment by lamont-granquist** [comment]
That was probably derp on my part, I'll bet I changed `platform` to `os` without changing the value.

**Comment by jaymzh** [comment]
it seems like platform -> osx is the right call here though.

I have a guy locally who has fixed a bunch of OSX bugs locally and wants to send PRs, if he gets to it today/tomorrow great, if not, I'll send a bunch.
