### ISSUE TITLE
sudo chef-server-ctl reconfigure

### ISSUE THREAD

**Issue by veera1989** [opscode/chef#2714]
Hi ,

Can anybody help me how to solve this issue.

================================================================================
Error executing action `create` on resource 'private-chef_pg_database[opscode-pgsql]'
================================================================================

Mixlib::ShellOut::ShellCommandFailed
------------------------------------
execute[create_database_opscode-pgsql] (/opt/opscode/embedded/cookbooks/private-chef/providers/pg_database.rb line 13) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of createdb --template template0 --encoding UTF-8 opscode-pgsql ----
STDOUT:
STDERR: createdb: could not connect to database template1: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
---- End output of createdb --template template0 --encoding UTF-8 opscode-pgsql ----
Ran createdb --template template0 --encoding UTF-8 opscode-pgsql returned 1

Resource Declaration:
---------------------
# In /opt/opscode/embedded/cookbooks/private-chef/recipes/postgresql.rb

127:   private_chef_pg_database "opscode-pgsql"
128:   include_recipe "private-chef::erchef_database"

Compiled Resource:
------------------
# Declared in /opt/opscode/embedded/cookbooks/private-chef/recipes/postgresql.rb:127:in `from_file'

private_chef_pg_database("opscode-pgsql") do
  action :create
  retries 0
  retry_delay 2
  guard_interpreter :default
  cookbook_name :"private-chef"
  recipe_name "postgresql"
  database "opscode-pgsql"
  template "template0"
  encoding "UTF-8"
end

Running handlers:
[2015-01-03T17:53:06+05:30] ERROR: Running exception handlers
Running handlers complete

[2015-01-03T17:53:06+05:30] ERROR: Exception handlers complete
[2015-01-03T17:53:06+05:30] FATAL: Stacktrace dumped to /opt/opscode/embedded/cookbooks/cache/chef-stacktrace.out
Chef Client failed. 8 resources updated in 95.206636436 seconds
[2015-01-03T17:53:06+05:30] FATAL: Mixlib::ShellOut::ShellCommandFailed: private-chef_pg_database[opscode-pgsql] (private-chef::postgresql line 127) had an error: Mixlib::ShellOut::ShellCommandFailed: execute[create_database_opscode-pgsql] (/opt/opscode/embedded/cookbooks/private-chef/providers/pg_database.rb line 13) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of createdb --template template0 --encoding UTF-8 opscode-pgsql ----
STDOUT:
STDERR: createdb: could not connect to database template1: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
---- End output of createdb --template template0 --encoding UTF-8 opscode-pgsql ----
Ran createdb --template template0 --encoding UTF-8 opscode-pgsql returned 1

**Comment by danielsdeleo** [comment]
Can you file your issue here: https://github.com/opscode/chef-server/issues ? Otherwise it won't be seen by the server team. Thanks!

**Comment by sridhar-ars** [comment]
Hi Guys,

I get the below errors when i try to install chef server  on RHEL ec2 instance

  * private-chef_pg_database[opscode-pgsql] action create
    * execute[create_database_opscode-pgsql] action run

      ================================================================================
      Error executing action `run` on resource 'execute[create_database_opscode-pgsql]'
      ================================================================================

      Mixlib::ShellOut::ShellCommandFailed
      ------------------------------------
      Expected process to exit with [0], but received '1'
      ---- Begin output of createdb --template template0 --encoding UTF-8 opscode-pgsql ----
      STDOUT:
      STDERR: createdb: could not connect to database template1: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
      ---- End output of createdb --template template0 --encoding UTF-8 opscode-pgsql ----
      Ran createdb --template template0 --encoding UTF-8 opscode-pgsql returned 1

      Resource Declaration:
      ---------------------
      # In /opt/opscode/embedded/cookbooks/cache/cookbooks/private-chef/providers/pg_database.rb

       13:   execute "create_database_#{new_resource.database}" do
       14:     command createdb_command
       15:     user node['private_chef']['postgresql']['username']
       16:     not_if {database_exist?}
       17:     retries 30
       18:   end
       19: end

      Compiled Resource:
      ------------------
      # Declared in /opt/opscode/embedded/cookbooks/cache/cookbooks/private-chef/providers/pg_database.rb:13:in `block in class_from_file'

      execute("create_database_opscode-pgsql") do
        action "run"
        retries 30
        retry_delay 2
        default_guard_interpreter :execute
        command "createdb --template template0 --encoding UTF-8 opscode-pgsql"
        backup 5
        returns 0
        user "opscode-pgsql"
        declared_type :execute
        cookbook_name "private-chef"
        not_if { #code block }
      end


    ================================================================================
    Error executing action `create` on resource 'private-chef_pg_database[opscode-pgsql]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    execute[create_database_opscode-pgsql] (/opt/opscode/embedded/cookbooks/cache/cookbooks/private-chef/providers/pg_database.rb line 13) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
    ---- Begin output of createdb --template template0 --encoding UTF-8 opscode-pgsql ----
    STDOUT:
    STDERR: createdb: could not connect to database template1: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
    ---- End output of createdb --template template0 --encoding UTF-8 opscode-pgsql ----
    Ran createdb --template template0 --encoding UTF-8 opscode-pgsql returned 1

    Resource Declaration:
    ---------------------
    # In /opt/opscode/embedded/cookbooks/cache/cookbooks/private-chef/recipes/postgresql.rb

    127:   private_chef_pg_database "opscode-pgsql"
    128:   include_recipe "private-chef::erchef_database"

    Compiled Resource:
    ------------------
    # Declared in /opt/opscode/embedded/cookbooks/cache/cookbooks/private-chef/recipes/postgresql.rb:127:in `from_file'

    private_chef_pg_database("opscode-pgsql") do
      action :create
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :private_chef_pg_database
      cookbook_name "private-chef"
      recipe_name "postgresql"
      database "opscode-pgsql"
      template "template0"
      encoding "UTF-8"
    end

Recipe: private-chef::rabbitmq
  * execute[restart_rabbitmq_log_service] action run
    - execute /opt/opscode/embedded/bin/sv restart /opt/opscode/sv/rabbitmq/log
Recipe: private-chef::postgresql
  * runit_service[postgresql] action restart
    - restart service runit_service[postgresql]
  * execute[restart_postgresql_log_service] action run
    - execute /opt/opscode/embedded/bin/sv restart /opt/opscode/sv/postgresql/log

Running handlers:
[2015-05-24T21:47:33-04:00] ERROR: Running exception handlers
Running handlers complete
[2015-05-24T21:47:33-04:00] ERROR: Exception handlers complete
[2015-05-24T21:47:33-04:00] FATAL: Stacktrace dumped to /opt/opscode/embedded/cookbooks/cache/chef-stacktrace.out
Chef Client failed. 75 resources updated in 239.283307751 seconds
[2015-05-24T21:47:34-04:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: private-chef_pg_database[opscode-pgsql] (private-chef::postgresql line 127) had an error: Mixlib::ShellOut::ShellCommandFailed: execute[create_database_opscode-pgsql] (/opt/opscode/embedded/cookbooks/cache/cookbooks/private-chef/providers/pg_database.rb line 13) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of createdb --template template0 --encoding UTF-8 opscode-pgsql ----
STDOUT:
STDERR: createdb: could not connect to database template1: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
---- End output of createdb --template template0 --encoding UTF-8 opscode-pgsql ----
Ran createdb --template template0 --encoding UTF-8 opscode-pgsql returned 1


Kindly share your inputs to overcome this error. 

REgards
Sridhar

**Comment by danielsdeleo** [comment]
Hi, this issue tracker is for Chef Client. The Chef Server issue tracker can be found here: https://github.com/opscode/chef-server/issues Your issue has been moved to https://github.com/chef/chef-server/issues/275
