### ISSUE TITLE
Leapsecond in 2015 announced

### ISSUE THREAD

**Issue by philpennock** [opscode/chef#2718]
There's a leapsecond in http://hpiers.obspm.fr/iers/bul/bulc/bulletinc.dat for the 2015 end-of-June window, Bulletin C 49.

I'm going to submit a PR to just pull in the updated leapseconds file from NIST.  I'm hoping to skip the CLA since the only text written by me is the commit message: I'm not the author of the change, I'm pulling in a semi-official reference update.  I'll include full details in the commit message, so that if this is a problem, then the change can be recreated by an allowed contributor, in a few seconds (beware poorly FTP server for fetching).

**Comment by juliandunn** [comment]
Is this issue intended for the `ntp` cookbook?

**Comment by lamont-granquist** [comment]
yeah, AFAIK we don't ship timezone files.  probably meant for the ntp cookbook.

**Comment by philpennock** [comment]
Please clarify, as I'm not familiar with the Chef/community process issues: this is a <http://community.opscode.com/cookbooks/ntp> update, in which the `CONTRIBUTING.md` file <https://github.com/gmiranda23/ntp/blob/master/CONTRIBUTING.md> explicitly references <http://tickets.opscode.com/> as the ticket tracker, which in turn starts with a banner "*IMPORTANT UPDATE* We've moved issue tracking from JIRA to Github Issues. Please see this blog post for more information, or go to the chef repository on Github to file an issue." which references _this_ repo's issue tracker.

The repo (which redirects to <https://github.com/gmiranda23/ntp>) has copyright notices in the `README.md` showing that the first/primary author is "Opscode, Inc." so it seemed reasonable that this was using the company's main ticketing system and central issue tracker.

If this is no longer the correct path, can you please chase down cleaning up the administrative references for contributions to stop pointing people here?

**Comment by lamont-granquist** [comment]
Again, the CONTRIBUTING.md file in the ntp cookbook needs to be updated, its all self-contained now -- the issue tracker is the issues on the github project for everything.
