### ISSUE TITLE
service action enable does not work on Linux Mint 17

### ISSUE THREAD

**Issue by rlipscombe** [opscode/chef#2726]
When using the 'postgresql' (https://supermarket.chef.io/cookbooks/postgresql) cookbook, chef-solo (v11.16.4) fails with:

    Error executing action `enable` on resource 'service[postgresql]'
    File '/etc/init/postgresql.conf' does not exist

This is because chef assumes that Linux Mint uses upstart; for the postgresql-9.3 package, it's still using init.d.

So the `action [:enable]` attribute does the wrong thing.

A similar problem occurs with the 'rabbitmq' cookbook (https://supermarket.chef.io/cookbooks/rabbitmq), which makes me think that this needs fixing in chef, rather than in the individual cookbooks.

**Comment by lamont-granquist** [comment]
No, those are bugs against the individual cookbooks, they should already have an if statement around the platform_version when the platform is ubuntu and they need another one around the platform_version when the platform is linuxmint.

**Comment by rlipscombe** [comment]
Cool, so how do I report a bug against the individual cookbooks? I might be being dim, but I can't find any link from (e.g.) https://supermarket.chef.io/cookbooks/rabbitmq where I might do that.

**Comment by lamont-granquist** [comment]
There should be a link to the github sources somewhere.  If not google `github cookbook rabbitmq` and its the top hit https://github.com/jjasghar/rabbitmq

**Comment by rlipscombe** [comment]
Also https://github.com/opscode/supermarket/issues/962.
