### ISSUE TITLE
Circular argument reference with ruby 2.2

### ISSUE THREAD

**Issue by jsternberg** [opscode/chef#2736]
When using the ruby 2.2 interpreter and the Chef library, I'll get this warning message:

```
/usr/local/lib/ruby/gems/2.2.0/gems/chef-12.0.3/lib/chef/data_bag_item.rb:161: warning: circular argument reference - data_bag
```

From a look at the file, there are a few different lines where the circular reference exists. Changing them from `data_bag=data_bag` to `data_bag=self.data_bag` should work to fix it.

**Comment by lamont-granquist** [comment]
dup of #2707

**Comment by venuinu** [comment]
thanks..i was scratching my head for hours.
