### ISSUE TITLE
Please update Nginx to the current release (1.6.2) to address security issues

### ISSUE THREAD

**Issue by donnorton** [opscode/chef#2744]
Chef 11 and Chef 12 both have Nginx v1.4 included (1.4.4 in Chef 11, and 1.4.3.6 in Chef 12).  Please update to 1.6.2 (or later) to address security concerns

**Comment by tyler-ball** [comment]
Hey @donnorton can you file this against https://github.com/opscode/chef-server please?  It is the chef server which uses Nginx and this repo is for the chef client.
