### ISSUE TITLE
Chef Server 12.0.1 does not work on Ubuntu 14.04

### ISSUE THREAD

**Issue by dgarstang** [opscode/chef#2761]
I believe chef server is broken in Ubuntu 14.04 with current updates.

This is Ubuntu 14.04
```
root@chefserver-001:/etc/init.d# cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.1 LTS"
```

Downloaded chef-server-core_12.0.1-1_amd64.deb. Installed package. 

Then,
```
root@chefserver-001:/etc/init.d# chef-server-ctl start
the ffi-yajl and yajl-ruby gems have incompatible C libyajl libs and should not be loaded in the same Ruby VM
falling back to ffi which might work (or might not, no promises)
ffi-yajl/json_gem is deprecated, these monkeypatches will be dropped shortly
```

After this, no chef server is running
```
root@chefserver-001:/etc/init.d# ps -ef | grep chef
root      2012  1921  0 18:24 pts/2    00:00:00 grep --color=auto chef
```

No logs are generated.

**Comment by lamont-granquist** [comment]
this is the client repo, its not for chef-server bugs and this is a dup of opscode/chef-server#53

**Comment by tylercloke** [comment]
I believe it is a separate issue than opscode/chef-server#53. I don't think the ffi-yajl warning is related to the chef-server not starting.
