### ISSUE TITLE
chef-solo --no-fork broken in Chef 12.0.3

### ISSUE THREAD

**Issue by tylercloke** [opscode/chef#2763]
(Just for context, trying to make chef-server use latest chef)

I get the following when running in `--no-fork` mode:

```
chef-solo --no-fork -l debug -c /opt/opscode/embedded/cookbooks/solo.rb -j /opt/opscode/embedded/cookbooks/dna.json
[2015-01-16T02:09:33+00:00] FATAL: NoMethodError: undefined method `size' for nil:NilClass
```

The above command runs fine if I remove the `--no-fork` part of the command.

Also looks like someone recently reported a similar issue via [stackexchange](http://stackoverflow.com/questions/27825707/chef-solo-fatal-nomethoderror-undefined-method-size-for-nilnilclass-when-ru).

Try as I might, I cannot get any more error output or a stack. It just straight crashes with that message.

**Comment by ranjib** [comment]
DUP https://github.com/opscode/chef/pull/2710

**Comment by tylercloke** [comment]
Thanks.
