### ISSUE TITLE
LDAP configuration on Open chef server

### ISSUE THREAD

**Issue by manojtailor27** [opscode/chef#2765]
I create chef-server.rb file and then adding following lines-

#ldap['host'] = 'example.com'
#ldap['port'] = '389'
#ldap['bind_dn'] = 'CN=users,OU=Not Sync,DC=example,DC=com'
#ldap['bind_password'] = 'abcd@1234'
#ldap['base_dn'] = 'DC=example,DC=com'
#ldap['ssl_enabled'] = 'false'
#ldap['login_attribute'] = 'sAMAccountName'

but after running the chef-server-ctl reconfigure command i am getting error like --

Relevant File Content:
----------------------
/opt/chef-server/embedded/cookbooks/chef-server/recipes/default.rb:

 27:  end.run_action(:create)
 28:  
 29:  if File.exists?("/etc/chef-server/chef-server.json")
 30:    Chef::Log.warn("Please move to /etc/chef-server/chef-server.rb for configuration - /etc/chef-server/chef-server.json is deprecated.")
 31:  else
 32:    ChefServer[:node] = node
 33:    if File.exists?("/etc/chef-server/chef-server.rb")
 34>>     ChefServer.from_file("/etc/chef-server/chef-server.rb")
 35:    end
 36:    node.consume_attributes(ChefServer.generate_config(node['fqdn']))
 37:  end
 38:  
 39:  if File.exists?("/var/opt/chef-server/bootstrapped")
 40:      node.set['chef_server']['bootstrap']['enable'] = false
 41:  end
 42:  
 43:  # Create the Chef User

Running handlers:
[2015-01-16T16:57:26+05:30] ERROR: Running exception handlers
Running handlers complete

[2015-01-16T16:57:26+05:30] ERROR: Exception handlers complete
[2015-01-16T16:57:26+05:30] FATAL: Stacktrace dumped to /opt/chef-server/embedded/cookbooks/cache/chef-stacktrace.out
Chef Client failed. 0 resources updated in 5.198391413 seconds
[2015-01-16T16:57:27+05:30] ERROR: wrong number of arguments (0 for 1)
[2015-01-16T16:57:27+05:30] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

**Comment by lamont-granquist** [comment]
This project is for chef client, you need to report this bug at http://github.com/opscode/chef-server.
