### ISSUE TITLE
rest-client version and Windows

### ISSUE THREAD

**Issue by awithersdd** [opscode/chef#2772]
Before rest-client 1.7.0 rest-client is broken on Windows. It creates Tempfile without setting binmode (see https://github.com/rest-client/rest-client/blob/v1.7.0/lib/restclient/request.rb#L456). This breaks anything using rest-client on Windows and expecting unaltered content.

**Comment by lamont-granquist** [comment]
chef 12 removed the rest-client dep entirely.
