### ISSUE TITLE
chef-full bootstrap template/script should respect chef_config[:chef_client_path] (aka. CHEF-5115)

### ISSUE THREAD

**Issue by dennis-benzinger-hybris** [opscode/chef#2783]
We would like to install the Chef Client in a custom directory. Therefore I reopen [CHEF-5115](https://tickets.opscode.com/browse/CHEF-5115) here:

> I realized on PR 1295 for CHEF-5102 that the chef-full script looks for a fixed chef-client location to determine if it needs to install or not, but the chef_config[:chef_client_path] setting can change that location.
> 
> We should fix this. There aren't any tests around this script, because that's hard, so we'll have to test it manually.

**Comment by rmoriz** [comment]
So it's just https://github.com/opscode/chef/blob/master/lib/chef/knife/bootstrap/chef-full.erb#L26 ?

You can use a custom bootstrap template, see https://docs.chef.io/knife_bootstrap.html#custom-templates

**Comment by dennis-benzinger-hybris** [comment]
Yes, this would probably fix [CHEF-5115](https://tickets.opscode.com/browse/CHEF-5115).
But if you want to install Chef Client in a custom directory that's only one half of the problem. It's just how the installation script checks if Chef Client is already installed. The installation itself is done by https://www.opscode.com/chef/install.sh.

**Comment by rmoriz** [comment]
IMHO:

If your business really takes value out of customizing the chef install location (which I doubt), consider forking and maintaining https://github.com/opscode/omnibus-chef and build your own installer-packages with it. The ```default_root``` can be overwritten and defaults to '/opt', see https://github.com/opscode/omnibus/blob/master/lib/omnibus/project.rb#L189 and https://github.com/opscode/omnibus-chef/blob/master/config/projects/chef.rb#L38

…or bootstrap using Ruby and rubygems.

But IMHO you should really consider going with the (sane) defaults of omnibus-chef. Maybe symlink /opt/ chef/ to another location of your choice, but stick with the other defaults.

**Comment by lamont-granquist** [comment]
@rmoriz just gave the correct answer.  internally we have a separate project which we build that installs into another location so that we can then use that chef to manage servers which build omnibus-chef in /opt/chef, so we wound up internally following that process.  a relocatable rpm/deb package is a hard problem and we won't be solving it any time soon.
